[build]
builder = "dockerfile"

[env]
LAVALINK_SERVER_PORT = "2333"
LAVALINK_SERVER_ADDRESS = "0.0.0.0"
LAVALINK_SERVER_PASSWORD = "youshallnotpass"
LAVALINK_SERVER_REGION = "us"

# Optional, but valid defaults
LAVALINK_SERVER_RATELIMIT_IPS = ""
LAVALINK_SERVER_RATELIMIT_RETRY_LIMIT = "5"
LAVALINK_SERVER_RATELIMIT_STRATEGY = "RotateOnBan"
